### ISSUE TITLE
LILT evaluation result

### ISSUE THREAD

**Issue by vishal-nayak1** [NielsRogge/Transformers-Tutorials#216]
Hi @NielsRogge, 

Thanks for adding the LILT model, i have a doubt that in the [notebook](https://github.com/NielsRogge/Transformers-Tutorials/blob/master/LiLT/Fine_tune_LiltForTokenClassification_on_FUNSD_(nielsr_funsd).ipynb) i find out that evaluation accuracy (F1 score, recall & precision) is not matching with the original [repository](https://github.com/jpWang/LiLT#semantic-entity-recognition-on-funsd-1), please clarify it.

**Comment by NielsRogge** [comment]
Hi,

Yes it depends on what type of bounding boxes you feed to the model. If you train LiLT on [nielsr/funsd-layoutlmv3](https://huggingface.co/datasets/nielsr/funsd-layoutlmv3), you'll see that you get 88-89% F1 score. However, training on [nielsr/funsd](https://huggingface.co/datasets/nielsr/funsd), you'll see you only get about 80% F1.

This is because the former uses so-called "segment positions", rather than "word positions". This means that all words that make up a certain segment in a document, like an address on an invoice, get the same bounding boxes (and hence will get the same position embeddings). This greatly improves performance, so it's always adviced to use an OCR engine that can recognize segments.

See this thread for more info: https://github.com/jpWang/LiLT/issues/28

**Comment by vishal-nayak1** [comment]
Thanks for sharing this.So, Layoutlmv3/LILT might fail to perform better during inference as if we dont have true/actual segment level information from OCR engine.

**Comment by ArlindNocaj** [comment]
Just use an OCR which provides also segment or paragraph information, e.g. TesseractOCR for example provides such segment information.
